### PR TITLE
Jsa/fruit log icon change

### PR DESCRIPTION
**Pull request by jsasasaaaaa**
Changes the quest image to fit the actual required items of the quest.

### CODE REVIEW

**Comment by Sheggies** [comment]
I'm no entirely sure whether we need a changelog text file. Ï'll open up a discussion about this.
Also, could you add a description? I have actually no idea why this has been changed and am not sure about its relevance. We have no issue that we can assign either.

**Comment by jsasasaaaaa** [comment]
> I'm no entirely sure whether we need a changelog text file. I'll open up a discussion about this. Also, could you add a description? I have actually no idea why this has been changed and am not sure about its relevance. We have no issue that we can assign either.

Ah, i changed it because the quest asks for bananas and blueberries while the image clearly had and orange, this triggered some people too

**Comment by Sheggies** [comment]
Alright, I'll approve as soon as you change the issue's description. The change itself looks alright 👍

**Review by Sheggies — APPROVED** [review]
Can be merged

**Pull request merged**
