### PR TITLE
Generated missing icons

### PR DESCRIPTION
**Pull request by jsasasaaaaa**
Generated some missing icons

### CODE REVIEW

**Review by Sheggies — DISMISSED** [review]
Although through no fault of your own, unfortunately the icon generation caused the XML file to shift and partially reorder the icon definitions :(

Could you address this so only the new icons are shown in the diff?

This of course means some tedious work and might be thrown away by the mod tool the next time icons are generated.

Do you know by chance how to prevent this from happening?

**Comment by jsasasaaaaa** [comment]
old
image

new
image

**Comment by Sheggies** [comment]
Alright I guess there will be no use to manually change the entries if the mod tool is going to ruin it again on the next icon generation.

**Comment by jsasasaaaaa** [comment]
And, the changed order of icons doesn't matter anyway, it makes it a little hard looking for the new icons generated, but it doesn't make a huge difference

**Review by Sheggies — APPROVED** [review]
Icon generation causing reordering of definitions will be ignored in future. PR is good to go 👌

**Pull request merged**
