### PR TITLE
Update changelog.txt

### PR DESCRIPTION
**Pull request by jsasasaaaaa**

### CODE REVIEW

**Review by june-cb — CHANGES_REQUESTED** [review]
In short these are the lines you should look over:

6: Harpoon (capitalised `h`)
7: Same as line 6
9: Use `Readded` or possibly `Reintroduced`
13: (Optional) More specific info of what has been fixed
17: Specify that `mod support system` refers to the custom craftbot recipes

**Comment by jsasasaaaaa** [comment]
i was just deleting stuff because the changelog has been pushed onto the workshop

**Comment by jsasasaaaaa** [comment]
and what do you want me to say for mod support system? i have no clue what Q Mark did to it

**Comment by Sheggies** [comment]
> and what do you want me to say for mod support system? i have no clue what Q Mark did to it

@QuestionableM could you jump in and help us out here? 😅

**Comment by QuestionableM** [comment]
The newest system that I've implemented throws 3 times less errors and it's also a bit faster.

**Comment by Sheggies** [comment]
Is it the custom craftbot recipes library that we're talking about?

**Comment by jsasasaaaaa** [comment]
the mod support system, yes

**Comment by Sheggies** [comment]
Ok, I've updated my original change request. As soon as you've committed those changes you'll get a green light 👍

**Comment by jsasasaaaaa** [comment]
done

**Comment by Sheggies** [comment]
> done

And don't forget to push them 😅

**Comment by jsasasaaaaa** [comment]
it's already on the workshop

**Comment by Sheggies** [comment]
Didn't know we were talking about the workshop 😄 
Could you **commit and push** the changes to this branch so they can be merged to `main`?

**Comment by jsasasaaaaa** [comment]
i just wanted to clear the changelog file for when we add new stuff, the things that were in the file have been posted on the workshop page of the mod, i was just clearing it so that we dont get confused with old and new changes, this is just a temporary file that i made a while ago to track changes and once we push and update, i post the changelog onto the workshop and clear this file

**Comment by Sheggies** [comment]
I see, maybe we should use the [releases](https://github.com/RaftMechanic/Raft-Mechanic-Game-Mode/releases) page instead then? 🤔

**Comment by jsasasaaaaa** [comment]
i dont think anyone is gonna download files from here are they?

**Comment by jsasasaaaaa** [comment]
because releases need files that you can download right?

**Comment by Sheggies** [comment]
While you can provide binaries, it's not necessary. Releases point to the commit of the tag they refer to. I've quickly created some tags that reflect the workshop updates as close as possible and the respective releases.

**Comment by jsasasaaaaa** [comment]
and how are we supposed to track changes if we dont use this file?

**Comment by Sheggies** [comment]
I should've mentioned my intentions, my bad.

The notes have been published on the releases page. We track changes via PRs and the commits they include. Github can (auto generate release notes)[https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes].

I'd like to use this feature instead of tracking a file that itself replicates the commit history that we already have.

**Comment by Sheggies** [comment]
We can merge your latest changes if you want. Let us decide whether we really want to use this file though, since it has little use considering we have the entire commit history and release notes can be generated in a few steps without manual intervention.

**Comment by jsasasaaaaa** [comment]
hmm, i see, okay then

**Comment by Sheggies** [comment]
As discussed, the file will be removed and the commit history used to generate change logs for new releases.

**Pull request closed without merging**
